import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Inter } from "next/font/google";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
    display: "swap",
});

export const poppins = Poppins({
    weight: ["400", "500", "600", "700"], // Add specific weights as needed
    subsets: ["latin"],
    variable: "--font-poppins",
    display: "swap",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${poppins.variable}`}>
                {children}
            </body>
        </html>
    );
}
